apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer-stateful-set
  labels:
    app: producer
spec:
  replicas: 1
  serviceName: "producer"
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - image: maoltr/rabbitmq-producer
          imagePullPolicy: Always
          name: rabbitmq-consumer
          env:
            - name: REPLICAS_COUNT
              value: "10"
            - name: MSG_RATE
              value: "1000"
            - name: MSG_COUNT
              value: "1000"
            - name: RABBITMQ_SERVER
              value: ""
            - name: HUB_COUNT
              value: "7000"

